name: Build add-on ZIP

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare folder
        run: |
          # Se la tua cartella plugin si chiama "addon", copiala in "onto3d"
          if [ -d "addon" ]; then
            rm -rf onto3d
            cp -r addon onto3d
          fi
          mkdir -p dist

      - name: Zip package
        run: zip -r "dist/onto3d-${GITHUB_REF_NAME}.zip" onto3d -x "*/.DS_Store" "*/__pycache__/*"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
