name: Build add-on ZIP

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check package folder
        run: |
          echo "Checking that 'onto3d/' exists..."
          ls -la
          test -d onto3d || (echo "❌ ERROR: 'onto3d/' folder not found at repo root" && exit 1)

      - name: Create dist directory
        run: mkdir -p dist

      - name: Zip add-on
        run: zip -r "dist/onto3d-${GITHUB_REF_NAME}.zip" onto3d -x "*/.DS_Store" "*/__pycache__/*"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
